# Model Configurations
hidden_size: 768
num_attention_heads: 12
intermediate_size: 3072
attention_dropout: 0.1
optimizer: "Adam"

# Training Configurations
batch_size: 8
learning_rate: 0.0001
epochs: 10
image_size: 224

# Paths
image_dir: "data/train"
output_image: "vision_output.png"

